aws_region           = "ap-south-1"
vpc_cidr             = "10.0.0.0/16"
vpc_name             = "my-vpc"
public_subnet_cidr   = "10.0.1.0/24"
private_subnet_cidr  = "10.0.2.0/24"
public_subnet_az     = "ap-south-1a"
private_subnet_az    = "ap-south-1b"
